// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewWorkData struct {
	CreateDataJs *string `json:"create_data_js"`
	Detail       *string `json:"detail"`
	Experience   *string `json:"experience"`
	IsShow       *bool   `json:"is_show"`
	Name         *string `json:"name"`
	Salary       int     `json:"salary"`
	Term         *string `json:"term"`
	Type         *string `json:"type"`
	Workdays     *string `json:"workdays"`
	WorkType     *string `json:"workType"`
}

type WorkData struct {
	ID           string  `json:"id"`
	CreateDataJs *string `json:"create_data_js"`
	Detail       *string `json:"detail"`
	Experience   *string `json:"experience"`
	IsShow       *bool   `json:"is_show"`
	Name         string  `json:"name"`
	Salary       int     `json:"salary"`
	Term         *string `json:"term"`
	Type         *string `json:"type"`
	Workdays     *string `json:"workdays"`
	WorkType     *string `json:"workType"`
}
